spring:
  data:
    mongodb:
      host: localhost
      port: 28017
      uri: mongodb://chat-messages-service-root:chat-messages-service-root-pass-123@localhost:28017/?authMechanism=DEFAULT
      database: chat_messages_service_database
      username: chat-messages-service-root
      password: chat-messages-service-root-pass-123
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq-user
    password: rabbitmq-pass-123
    listener:
      simple:
        default-requeue-rejected: false
server:
  port: 9996

logging:
  level:
    pl:
      kubaretip:
        chatmessagesservice: debug
