spring:
  data:
    mongodb:
      host: chat-messages-service-mongo
      port: 28017
      uri: mongodb://chat-messages-service-root:chat-messages-service-root-pass-123@localhost:28017/?authMechanism=DEFAULT
      database: chat_messages_service_database
      username: chat-messages-service-root
      password: chat-messages-service-root-pass-123
  rabbitmq:
    host: rabbitmq-service
    port: 5672
    username: rabbitmq-user
    password: rabbitmq-pass-123

logging:
  level:
    pl:
      kubaretip:
        chatmessagesservice: debug
